local M = {}

-- Configuración por defecto

M.data = {
	-- Otras categorías...
	--
	["📂 types"] = {
		folder = "📂",
		files = "📄",
		database = "🗄️",
		spreadsheet = "📊",
		powerpoint = "📑",
		image = "🖼️",
		video = "📹",
		audio = "🎵",
		zip = "📦",
		pdf = "📕",
		code = "</>",
	},
	["  play"] = {
		play = "", -- Icono de play alternativo
		pausa = "", -- Icono de pausa alternativo
		stop = "", -- Icono de stop alternativo
		avanzar = "", -- Icono de siguiente alternativo
		retroceder = "", -- Icono de anterior alternativo
		final = "",
		principio = "",
		siguiente = " ",
		anterior = " ",
	},
	["🔊 media"] = {
		grabar = "●", -- Icono de grabar alternativo   play = "", -- Icono de play
		volumen_alto = "🔊", -- Icono de volumen alto
		volumen_bajo = "🔉", -- Icono de volumen bajo
		silencio = "🔇", -- Icono de silencio
		microfono = "🎤", -- Icono de micrófono
		camara = "📷", -- Icono de cámara
		altavoz = "🔈", -- Icono de altavoz
		auriculares = "🎧", -- Icono de auriculares
		musica = "🎵", -- Icono de música
		nota_musical = "🎶", -- Icono de notas musicales
		pelicula = "🎬", -- Icono de película
		television = "📺", -- Icono de televisión
		radio = "📻", -- Icono de radio
		reloj = "󰥔", -- Icono de reloj (cronómetro)
	},

	["🇪🇸banderas"] = {
		["España"] = "🇪🇸", -- Bandera de España
		["Estados unidos"] = "🇺🇸", -- Bandera de Estados Unidos
		Mexico = "🇲🇽", -- Bandera de México
		Argentina = "🇦🇷", -- Bandera de Argentina
		Brasil = "🇧🇷", -- Bandera de Brasil
		Francia = "🇫🇷", -- Bandera de Francia
		Alemania = "🇩🇪", -- Bandera de Alemania
		Italia = "🇮🇹", -- Bandera de Italia
		["Reino unido"] = "🇬🇧", -- Bandera del Reino Unido
		Canada = "🇨🇦", -- Bandera de Canadá
		Australia = "🇦🇺", -- Bandera de Australia
		Japon = "🇯🇵", -- Bandera de Japón
		China = "🇨🇳", -- Bandera de China
		Rusia = "🇷🇺", -- Bandera de Rusia
		India = "🇮🇳", -- Bandera de India
		Sudafrica = "🇿🇦", -- Bandera de Sudáfrica
		["Corea del sur"] = "🇰🇷", -- Bandera de Corea del Sur
		Suecia = "🇸🇪", -- Bandera de Suecia
		Noruega = "🇳🇴", -- Bandera de Noruega
		Finlandia = "🇫🇮", -- Bandera de Finlandia
		Dinamarca = "🇩🇰", -- Bandera de Dinamarca
		Portugal = "🇵🇹", -- Bandera de Portugal
		Grecia = "🇬🇷", -- Bandera de Grecia
		Turquia = "🇹🇷", -- Bandera de Turquía
		Egipto = "🇪🇬", -- Bandera de Egipto
		["Nueva zelanda"] = "🇳🇿", -- Bandera de Nueva Zelanda
		Suiza = "🇨🇭", -- Bandera de Suiza
		Austria = "🇦🇹", -- Bandera de Austria
		Belgica = "🇧🇪", -- Bandera de Bélgica
		Holanda = "🇳🇱", -- Bandera de Holanda
		Irlanda = "🇮🇪", -- Bandera de Irlanda
		Polonia = "🇵🇱", -- Bandera de Polonia
		Ucrania = "🇺🇦", -- Bandera de Ucrania
		Israel = "🇮🇱", -- Bandera de Israel
		["Arabia saudita"] = "🇸🇦", -- Bandera de Arabia Saudita
		["Emiratos arabes unidos"] = "🇦🇪", -- Bandera de Emiratos Árabes Unidos
		Qatar = "🇶🇦", -- Bandera de Qatar
		Singapur = "🇸🇬", -- Bandera de Singapur
		Tailandia = "🇹🇭", -- Bandera de Tailandia
		Vietnam = "🇻🇳", -- Bandera de Vietnam
		Filipinas = "🇵🇭", -- Bandera de Filipinas
		Malasia = "🇲🇾", -- Bandera de Malasia
		Indonesia = "🇮🇩", -- Bandera de Indonesia
		Pakistan = "🇵🇰", -- Bandera de Pakistán
		Bangladesh = "🇧🇩", -- Bandera de Bangladesh
		["Sri lanka"] = "🇱🇰", -- Bandera de Sri Lanka
		Iran = "🇮🇷", -- Bandera de Irán
		Irak = "🇮🇶", -- Bandera de Irak
		Siria = "🇸🇾", -- Bandera de Siria
		Libano = "🇱🇧", -- Bandera de Líbano
		Jordania = "🇯🇴", -- Bandera de Jordania
		Marruecos = "🇲🇦", -- Bandera de Marruecos
		Argelia = "🇩🇿", -- Bandera de Argelia
		Tunez = "🇹🇳", -- Bandera de Túnez
		Kenia = "🇰🇪", -- Bandera de Kenia
		Nigeria = "🇳🇬", -- Bandera de Nigeria
		Ghana = "🇬🇭", -- Bandera de Ghana
		Etiopia = "🇪🇹", -- Bandera de Etiopía
		Sudan = "🇸🇩", -- Bandera de Sudán
		Somalia = "🇸🇴", -- Bandera de Somalia
		Uganda = "🇺🇬", -- Bandera de Uganda
		Tanzania = "🇹🇿", -- Bandera de Tanzania
		Zambia = "🇿🇲", -- Bandera de Zambia
		Zimbabwe = "🇿🇼", -- Bandera de Zimbabue
		Botswana = "🇧🇼", -- Bandera de Botsuana
		Namibia = "🇳🇦", -- Bandera de Namibia
		Mozambique = "🇲🇿", -- Bandera de Mozambique
		Madagascar = "🇲🇬", -- Bandera de Madagascar
		Mauricio = "🇲🇺", -- Bandera de Mauricio
		Seychelles = "🇸🇨", -- Bandera de Seychelles
		Comoras = "🇰🇲", -- Bandera de Comoras
		["Cabo verde"] = "🇨🇻", -- Bandera de Cabo Verde
		["Guinea ecuatorial"] = "🇬🇶", -- Bandera de Guinea Ecuatorial
		Gabon = "🇬🇦", -- Bandera de Gabón
		Camerun = "🇨🇲", -- Bandera de Camerún
		["Republica centroafricana"] = "🇨🇫", -- Bandera de la República Centroafricana
		Chad = "🇹🇩", -- Bandera de Chad
		Niger = "🇳🇪", -- Bandera de Níger
		Mali = "🇲🇱", -- Bandera de Malí
		["Burkina faso"] = "🇧🇫", -- Bandera de Burkina Faso
		Benin = "🇧🇯", -- Bandera de Benín
		Togo = "🇹🇬", -- Bandera de Togo
		["Costa de marfil"] = "🇨🇮", -- Bandera de Costa de Marfil
		Liberia = "🇱🇷", -- Bandera de Liberia
		["Sierra leona"] = "🇸🇱", -- Bandera de Sierra Leona
		Guinea = "🇬🇳", -- Bandera de Guinea
		["Guinea bissau"] = "🇬🇼", -- Bandera de Guinea-Bisáu
		Senegal = "🇸🇳", -- Bandera de Senegal
		Gambia = "🇬🇲", -- Bandera de Gambia
		Mauritania = "🇲🇷", -- Bandera de Mauritania
		Yemen = "🇾🇪", -- Bandera de Yemen
		Oman = "🇴🇲", -- Bandera de Omán
		Kuwait = "🇰🇼", -- Bandera de Kuwait
		Bahrein = "🇧🇭", -- Bandera de Bahréin
		Maldivas = "🇲🇻", -- Bandera de Maldivas
		Brunei = "🇧🇳", -- Bandera de Brunéi
		["Timor oriental"] = "🇹🇱", -- Bandera de Timor Oriental
		Fiji = "🇫🇯", -- Bandera de Fiyi
		Samoa = "🇼🇸", -- Bandera de Samoa
		Tonga = "🇹🇴", -- Bandera de Tonga
		["Islas salomon"] = "🇸🇧", -- Bandera de las Islas Salomón
		Vanuatu = "🇻🇺", -- Bandera de Vanuatu
		["Papua nueva guinea"] = "🇵🇬", -- Bandera de Papúa Nueva Guinea
		["Islas marshall"] = "🇲🇭", -- Bandera de las Islas Marshall
		Micronesia = "🇫🇲", -- Bandera de Micronesia
		Palau = "🇵🇼", -- Bandera de Palaos
		Nauru = "🇳🇷", -- Bandera de Nauru
		Kiribati = "🇰🇮", -- Bandera de Kiribati
		Tuvalu = "🇹🇻", -- Bandera de Tuvalu
		["Islas cook"] = "🇨🇰", -- Bandera de las Islas Cook
		Niue = "🇳🇺", -- Bandera de Niue
		Tokelau = "🇹🇰", -- Bandera de Tokelau
		["Islas faroe"] = "🇫🇴", -- Bandera de las Islas Feroe
		Groenlandia = "🇬🇱", -- Bandera de Groenlandia
		["Isla de man"] = "🇮🇲", -- Bandera de la Isla de Man
		Jersey = "🇯🇪", -- Bandera de Jersey
		Guernsey = "🇬🇬", -- Bandera de Guernsey
		Gibraltar = "🇬🇮", -- Bandera de Gibraltar
		Bermudas = "🇧🇲", -- Bandera de Bermudas
		["Islas caiman"] = "🇰🇾", -- Bandera de las Islas Caimán
		["Islas virgenes britanicas"] = "🇻🇬", -- Bandera de las Islas Vírgenes Británicas
		["Islas virgenes estadounidenses"] = "🇻🇮", -- Bandera de las Islas Vírgenes Estadounidenses
		["Puerto rico"] = "🇵🇷", -- Bandera de Puerto Rico
		Guam = "🇬🇺", -- Bandera de Guam
		["Samoa americana"] = "🇦🇸", -- Bandera de Samoa Americana
		["Islas marianas del norte"] = "🇲🇵", -- Bandera de las Islas Marianas del Norte
		Palestina = "🇵🇸", -- Bandera de Palestina
		["Sahara occidental"] = "🇪🇭", -- Bandera del Sáhara Occidental
		Taiwan = "🇹🇼", -- Bandera de Taiwán
		["Hong kong"] = "🇭🇰", -- Bandera de Hong Kong
		Macao = "🇲🇴", -- Bandera de Macao
		Kosovo = "🇽🇰", -- Bandera de Kosovo
		Abjasia = "🇦🇧", -- Bandera de Abjasia
		["Osetia del sur"] = "🇴🇸", -- Bandera de Osetia del Sur
		Transnistria = "🇵🇲", -- Bandera de Transnistria
		Artsaj = "🇦🇿", -- Bandera de Artsaj
		Somalilandia = "🇸🇴", -- Bandera de Somalilandia
		Sealand = "🇸🇱", -- Bandera de Sealand
		["Orden de malta"] = "🇲🇹", -- Bandera de la Orden de Malta
		["Union europea"] = "🇪🇺", -- Bandera de la Unión Europea
		Onu = "🇺🇳", -- Bandera de la ONU
		Otan = "🇳🇹", -- Bandera de la OTAN
		Oea = "🇴🇦", -- Bandera de la OEA
		Ue = "🇪🇺", -- Bandera de la UE
	},
	["😊 gestos"] = {
		feliz = "😊",
		triste = "😢",
		enojado = "😠",
		sorprendido = "😮",
		pensativo = "🤔",
		asustado = "😨",
		enamorado = "😍",
		riendo = "😂",
		guinyo = "😉",
		beso = "😘",
		neutral = "😐",
		dormido = "😴",
		enfermo = "🤒",
		confundido = "😕",
		avergonzado = "😳",
		cool = "😎",
		llorando = "😭",
		gritando = "😱",
		silbando = "😗",
		besos = "🥰",
	},
	["🍎 comida"] = {
		manzana = "🍎",
		platano = "🍌",
		uvas = "🍇",
		fresa = "🍓",
		sandia = "🍉",
		naranja = "🍊",
		limon = "🍋",
		melocoton = "🍑",
		cereza = "🍒",
		pera = "🍐",
		kiwi = "🥝",
		mango = "🥭",
		["piña"] = "🍍",
		coco = "🥥",
		berenjena = "🍆",
		zanahoria = "🥕",
		maiz = "🌽",
		pimiento = "🫑",
		tomate = "🍅",
		lechuga = "🥬",
		brocoli = "🥦",
		ajo = "🧄",
		cebolla = "🧅",
		patata = "🥔",
		batata = "🍠",
		pan = "🍞",
		croissant = "🥐",
		baguette = "🥖",
		pretzel = "🥨",
		queso = "🧀",
		huevo = "🥚",
		bacon = "🥓",
		carne = "🥩",
		pollo = "🍗",
		pescado = "🐟",
		camarones = "🦐",
		cangrejo = "🦀",
		calamar = "🦑",
		sushi = "🍣",
		dango = "🍡",
		donut = "🍩",
		galleta = "🍪",
		pastel = "🍰",
		cupcake = "🧁",
		helado = "🍨",
		paleta = "🍭",
		chocolate = "🍫",
		caramelo = "🍬",
		miel = "🍯",
		palomitas = "🍿",
		salchicha = "🌭",
		pizza = "🍕",
		hamburguesa = "🍔",
		patatas_fritas = "🍟",
		taco = "🌮",
		burrito = "🌯",
		falafel = "🧆",
		huevo_frito = "🍳",
		ensalada = "🥗",
		sopa = "🍲",
		olla = "🍜",
		tazon = "🍚",
		cuchara = "🥄",
		tenedor = "🍴",
		cuchillo = "🔪",
		plato = "🍽️",
		copa = "🍷",
		cerveza = "🍺",
		sake = "🍶",
		te = "🍵",
		cafe = "☕",
		batido = "🥤",
		bebida = "🧃",
		botella = "🍾",
		vaso = "🥃",
		copa_cocktail = "🍸",
		copa_champagne = "🍾",
	},
	["🚗 Señales de tráfico"] = {
		semaforo = "🚦",
		stop = "🛑",
		ceda_el_paso = "⛔",
		direccion_prohibida = "🚫",
		prohibido_estacionar = "🚷",
		prohibido_circular = "🚳",
		prohibido_adelantar = "🚷",
		prohibido_entrar = "⛔",
		obras = "🚧",
		animales_sueltos = "🐾",
		["niños"] = "🚸",
		bicicletas = "🚲",
		zona_escolar = "🚸",
		zona_hospital = "🏥",
		zona_residencial = "🏘️",
		zona_comercial = "🏬",
		zona_industrial = "🏭",
		carretera = "🛣️",
		puente = "🌉",
		tunel = "🚇",
		area_descanso = "🛋️",
		gasolinera = "⛽",
		taller = "🔧",
		telefono_emergencia = "📞",
		policia = "👮",
		ambulancia = "🚑",
		bomberos = "🚒",
		estacionamiento_discapacitados = "♿",
	},
	["🔧 herramientas"] = {
		martillo = "🔨",
		destornillador = "🪛",
		llave_inglesa = "🔧",
		sierra = "🪚",
		taladro = "🪛",
		ordenador = "💻",
		raton = "🖱️",
		impresora = "🖨️",
		disco_duro = "💽",
		usb = "💾",
		ladrillo = "🧱",
		escalera = "🪜",
		pincel = "🖌️",
		rotulador = "🖍️",
		pintura = "🎨",
		lienzo = "🖼️",
		paleta = "🎨",
	},
	["✋ Manos"] = {
		["👋 Gestos"] = {
			saludar = "👋", -- Mover la mano (hola/adiós)
			paz = "✌️", -- Signo de paz/victoria
			ok = "👌", -- Gestos de aprobación
			pulgar_arriba = "👍", -- De acuerdo/bien
			pulgar_abajo = "👎", -- En desacuerdo/mal
			["señalar"] = "👉", -- Indicar dirección
			["puño"] = "✊", -- Fuerza/determinación
			mano_alzada = "✋", -- Detener/preguntar
			aplaudir = "👏", -- Aplausos
			te_quiero = "🤟", -- Lenguaje de señas "te quiero"
			llamame = "🤙", -- Gestos de "llámame"
			rock = "🤘", -- Gestos de música rock
			cruzar_dedos = "🤞", -- Para desear suerte
			pellizco = "🤏", -- Algo pequeño/precisión
		},

		["🙏 Acciones"] = {
			rezar = "🙏", -- Oración/agradecimiento
			["apretón_manos"] = "🤝", -- Saludo/acuerdo
			chocar_los_cinco = "✋", -- Celebración
			escribir = "✍️", -- Acción de escribir
			agarrar = "🫴", -- Tomar/sostener algo
			mano_abierta = "🖐️", -- Mano extendida
			palmas_arriba = "🤲", -- Ofrecer/recibir
			palmas_abajo = "🖐️", -- Mano hacia abajo
		},

		["🖐️ Variaciones"] = {
			mano_izquierda = "🫲", -- Orientación izquierda
			mano_derecha = "🫱", -- Orientación derecha
			detener = "✋", -- Señal de stop
			dedos_separados = "🖐️", -- Mano abierta con dedos abiertos
			gesto_ofensivo = "🖕", -- Gestos groseros (opcional)
		},
	},
}

-- Función para permitir al usuario sobrescribir la configuración
function M.setup(user_config)
	if user_config and user_config.data then
		M.data = vim.tbl_deep_extend("force", M.data, user_config.data)
	end
end

-- Cargar los datos desde 'data.lua'

return M
